name: Whack a bug API

on:
  push:
    branches: [main, dev]
  pull:
    brances: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          -m python pip install --upgrade pip
          pip install -r requirements.txt;
      - name: Test with unittest
        run: |
          python -m unittest
